# Configuración de la Mesa de Votación
mesa.host=localhost
mesa.base.port=10000
mesa.adapter.name=MesaAdapter
mesa.category=RecibirCandidatos

# Configuración de IceGrid
icegrid.registry.host=localhost
icegrid.registry.port=4061

# Configuración de Endpoints
endpoints.format=tcp -h ${mesa.host} -p %d 