q//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `System.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public class Ack implements java.lang.Cloneable,
                            java.io.Serializable
{
    public long idVoto;

    public boolean registrado;

    public String mensaje;

    public Ack()
    {
        this.mensaje = "";
    }

    public Ack(long idVoto, boolean registrado, String mensaje)
    {
        this.idVoto = idVoto;
        this.registrado = registrado;
        this.mensaje = mensaje;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Ack r = null;
        if(rhs instanceof Ack)
        {
            r = (Ack)rhs;
        }

        if(r != null)
        {
            if(this.idVoto != r.idVoto)
            {
                return false;
            }
            if(this.registrado != r.registrado)
            {
                return false;
            }
            if(this.mensaje != r.mensaje)
            {
                if(this.mensaje == null || r.mensaje == null || !this.mensaje.equals(r.mensaje))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::Demo::Ack");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, idVoto);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, registrado);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, mensaje);
        return h_;
    }

    public Ack clone()
    {
        Ack c = null;
        try
        {
            c = (Ack)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeLong(this.idVoto);
        ostr.writeBool(this.registrado);
        ostr.writeString(this.mensaje);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.idVoto = istr.readLong();
        this.registrado = istr.readBool();
        this.mensaje = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Ack v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Ack ice_read(com.zeroc.Ice.InputStream istr)
    {
        Ack v = new Ack();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Ack> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Ack v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Ack> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Ack.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Ack _nullMarshalValue = new Ack();

    /** @hidden */
    public static final long serialVersionUID = -1620937068L;
}
