//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `System.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public class Candidato implements java.lang.Cloneable,
                                  java.io.Serializable
{
    public long idCandidato;

    public String nombre;

    public Candidato()
    {
        this.nombre = "";
    }

    public Candidato(long idCandidato, String nombre)
    {
        this.idCandidato = idCandidato;
        this.nombre = nombre;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Candidato r = null;
        if(rhs instanceof Candidato)
        {
            r = (Candidato)rhs;
        }

        if(r != null)
        {
            if(this.idCandidato != r.idCandidato)
            {
                return false;
            }
            if(this.nombre != r.nombre)
            {
                if(this.nombre == null || r.nombre == null || !this.nombre.equals(r.nombre))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::Demo::Candidato");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, idCandidato);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, nombre);
        return h_;
    }

    public Candidato clone()
    {
        Candidato c = null;
        try
        {
            c = (Candidato)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeLong(this.idCandidato);
        ostr.writeString(this.nombre);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.idCandidato = istr.readLong();
        this.nombre = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Candidato v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Candidato ice_read(com.zeroc.Ice.InputStream istr)
    {
        Candidato v = new Candidato();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Candidato> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Candidato v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Candidato> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Candidato.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Candidato _nullMarshalValue = new Candidato();

    /** @hidden */
    public static final long serialVersionUID = 1104062172L;
}
